version: "3.4"

services:
  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb.rule=Host(`mariadb.localhost`)"

