# Use postgres/postgres user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: $PGDATA
    volumes:
      - ./data/postgres:$PGDATA
    ports:
      - 5432:5432

  admin:
    image: dpage/pgadmin4
    restart: always
    links:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
    ports:
      - 8080:80
      # - 4343:443