#!/usr/bin/env bash

# create .env file
if [ ! -f "${PWD}/.env" ]
then
    cp .env.example .env
fi

read -p "Set MongoDB root username? (default = N) (Y/N): " confirm 
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]
then
    read -p "Enter MongoDB root username: " username

    if [ $(./scripts/checkos) == "Mac" ]
    then
        sed -i "" "s/^MONGO_INITDB_ROOT_USERNAME=.*/MONGO_INITDB_ROOT_USERNAME=${username}/" ${PWD}/.env
    else
        sed -i "s/^MONGO_INITDB_ROOT_USERNAME=.*/MONGO_INITDB_ROOT_USERNAME=${username}/" ${PWD}/.env
    fi
    echo "Username set successfully"
fi

read -p "Set MongoDB root password? (default = N) (Y/N): " confirm 
if [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]]
then
    read -p "Enter MongoDB root password: " password

    if [ $(./scripts/checkos) == "Mac" ]
    then
        sed -i "" "s/^MONGO_INITDB_ROOT_PASSWORD=.*/MONGO_INITDB_ROOT_PASSWORD=${password}/" ${PWD}/.env
    else
        sed -i "s/^MONGO_INITDB_ROOT_PASSWORD=.*/MONGO_INITDB_ROOT_PASSWORD=${password}/" ${PWD}/.env
    fi
    echo "Password set successfully"
fi

echo "Starting docker container"
docker-compose up -d